services:
  - type: web
    name: virtual-sparkles
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_CREDS_JSON
        sync: false
      - key: SHEET_ID
        sync: false
